/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_vs_php;

import java.util.Random;

/**
 *
 * @author User
 */
public class bahasafavorit extends javax.swing.JFrame {
    private int skorjava = 0;
    private int skorphp = 0;
    private int skortotal = 0;
   
    /**
     * Creates new form bahasafavorit
     */
    public bahasafavorit() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labeljudul = new javax.swing.JLabel();
        labelsukajava = new javax.swing.JLabel();
        labeljava = new javax.swing.JLabel();
        labelphp = new javax.swing.JLabel();
        labelsukaphp = new javax.swing.JLabel();
        labeltotal = new javax.swing.JLabel();
        labelsukatotal = new javax.swing.JLabel();
        btnphp = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        persenjavaphp = new javax.swing.JProgressBar();
        btnjava = new javax.swing.JButton();
        labeljudul1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeljudul.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        labeljudul.setForeground(new java.awt.Color(255, 255, 153));
        labeljudul.setText("Pilihan Anda");
        getContentPane().add(labeljudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 180, 40));

        labelsukajava.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        labelsukajava.setText("0");
        getContentPane().add(labelsukajava, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        labeljava.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        labeljava.setForeground(new java.awt.Color(0, 0, 153));
        labeljava.setText("Java");
        getContentPane().add(labeljava, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 150, 60, -1));

        labelphp.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        labelphp.setForeground(new java.awt.Color(0, 0, 153));
        labelphp.setText("PHP");
        getContentPane().add(labelphp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        labelsukaphp.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        labelsukaphp.setText("0");
        getContentPane().add(labelsukaphp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        labeltotal.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labeltotal.setForeground(new java.awt.Color(255, 255, 102));
        labeltotal.setText("Partisipan =");
        getContentPane().add(labeltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 170, 170));

        labelsukatotal.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        labelsukatotal.setText("0");
        getContentPane().add(labelsukatotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 190, 350));

        btnphp.setBackground(new java.awt.Color(153, 0, 153));
        btnphp.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnphp.setForeground(new java.awt.Color(255, 255, 255));
        btnphp.setText("Vote");
        btnphp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphpActionPerformed(evt);
            }
        });
        getContentPane().add(btnphp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        btnreset.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, 40));

        persenjavaphp.setBackground(new java.awt.Color(102, 255, 102));
        persenjavaphp.setForeground(new java.awt.Color(0, 0, 0));
        persenjavaphp.setStringPainted(true);
        getContentPane().add(persenjavaphp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 350, 40));

        btnjava.setBackground(new java.awt.Color(153, 0, 153));
        btnjava.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnjava.setForeground(new java.awt.Color(255, 255, 255));
        btnjava.setText("Vote");
        btnjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjavaActionPerformed(evt);
            }
        });
        getContentPane().add(btnjava, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        labeljudul1.setBackground(new java.awt.Color(255, 255, 102));
        labeljudul1.setFont(new java.awt.Font("Berlin Sans FB", 1, 30)); // NOI18N
        labeljudul1.setForeground(new java.awt.Color(255, 255, 102));
        labeljudul1.setText("Bahasa Pemrograman ");
        getContentPane().add(labeljudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 350, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("By : Chandra Purnama W - 21120117130070");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 450, 310, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nilai persen menunjukan nilai dari Java");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 290, 80));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjavaActionPerformed
       for (int counter =1; counter<=1; counter++){                      
                skorjava = ++skorjava;   
        }
    labelsukajava.setText(String.valueOf(skorjava));
    labelsukatotal.setText(String.valueOf(skorjava+skorphp));
    persenjavaphp.setValue(skorjava);
    persenjavaphp.setMaximum(skorjava+skorphp);
    }//GEN-LAST:event_btnjavaActionPerformed

    private void btnphpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphpActionPerformed
        for (int counter =1; counter<=1; counter++){                      
                skorphp = ++skorphp;   
        }
    labelsukaphp.setText(String.valueOf(skorphp));
    labelsukatotal.setText(String.valueOf(skorjava+skorphp));
    persenjavaphp.setValue(skorjava);
    persenjavaphp.setMaximum(skorjava+skorphp);
    }//GEN-LAST:event_btnphpActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
       skorjava=0;
       skorphp=0;
       skortotal=0;
       labelsukaphp.setText(String.valueOf(skorphp));
       labelsukajava.setText(String.valueOf(skorjava));
       labelsukatotal.setText(String.valueOf(skortotal));
       persenjavaphp.setMaximum(100);
       persenjavaphp.setValue(0);
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bahasafavorit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bahasafavorit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bahasafavorit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bahasafavorit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bahasafavorit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnjava;
    private javax.swing.JButton btnphp;
    private javax.swing.JButton btnreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labeljava;
    private javax.swing.JLabel labeljudul;
    private javax.swing.JLabel labeljudul1;
    private javax.swing.JLabel labelphp;
    private javax.swing.JLabel labelsukajava;
    private javax.swing.JLabel labelsukaphp;
    private javax.swing.JLabel labelsukatotal;
    private javax.swing.JLabel labeltotal;
    private javax.swing.JProgressBar persenjavaphp;
    // End of variables declaration//GEN-END:variables
}
